# Gunakan Node.js versi LTS
FROM node:18

# Set working directory di container
WORKDIR /app

# Copy package.json & package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua source code
COPY . .

# Expose port yang digunakan (Zeabur otomatis baca $PORT)
EXPOSE 8080

# Jalankan server
CMD ["npm", "start"]
